import { allowedDomains, categories, portals, supportTickets, users } from '@/lib/data'; import { StatusBadge } from './PortalCard';
export function AdminStats(){return <div className="grid gap-4 md:grid-cols-4">{[['Users',users.length],['Portals',portals.length],['Domains',allowedDomains.length],['Tickets',supportTickets.length]].map(([k,v])=><div className="card" key={k}><p className="text-sm text-slate-500">{k}</p><p className="mt-2 text-3xl font-black text-navy">{v}</p></div>)}</div>}
export function UserTable(){return <Table heads={['Name','Email','Role','Status']} rows={users.map(u=>[u.name,u.email,u.role,u.status])}/>}
export function PortalTable(){return <div className="card overflow-x-auto"><div className="mb-4 flex gap-3"><input className="input" placeholder="Search portals"/><button className="btn-primary whitespace-nowrap">Add portal</button></div><table className="w-full text-left text-sm"><thead><tr><th>Name</th><th>Category</th><th>Department</th><th>Status</th><th>Actions</th></tr></thead><tbody>{portals.map(p=><tr className="border-t" key={p.id}><td className="py-3 font-semibold">{p.name}</td><td>{p.category}</td><td>{p.department}</td><td><StatusBadge status={p.status}/></td><td>Edit · Deactivate</td></tr>)}</tbody></table></div>}
export function DomainTable(){return <Table heads={['Domain','Description','Status','Actions']} rows={allowedDomains.map(d=>[d.domain,d.description,d.status,'Edit · Deactivate'])}/>}
export function CategoryTable(){return <Table heads={['Category','Description','Status']} rows={categories.map(c=>[c.name,c.description,c.status])}/>}
export function DocumentTable(){return <Table heads={['Portal','Document','Type','Visibility']} rows={portals.flatMap(p=>p.documents.map(d=>[p.name,d.title,d.type,d.visibility]))}/>}
export function SupportTable(){return <Table heads={['Ticket','Requester','Category','Subject','Status']} rows={supportTickets.map(t=>[t.ticketNumber,t.requester,t.category,t.subject,t.status])}/>}
function Table({heads, rows}:{heads:string[]; rows:string[][]}){return <div className="card overflow-x-auto"><div className="mb-4 flex gap-3"><input className="input" placeholder="Search and filter"/><button className="btn-primary whitespace-nowrap">Add / update</button></div><table className="w-full text-left text-sm"><thead><tr>{heads.map(h=><th className="py-2" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr className="border-t" key={i}>{r.map((c,j)=><td className="py-3 pr-4" key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
